#include <libraries/mui.h>
#include <proto/muimaster.h>
#include <clib/exec_protos.h>
#include <exec/memory.h>
#include <clib/alib_protos.h>

struct ObjApp
{
	APTR	App;
	APTR	WI_Cmd;
	APTR	BT_Zoom;
	APTR	BT_Zoom_Out;
	APTR	BT_Redraw;
	APTR	BT_Zoom_Reset;
	APTR	BT_Info;
	APTR	CY_Proj;
	APTR	TX_lon;
	APTR	TX_lat;
	APTR	TX_Selectionne;
	APTR	TX_courant;
	APTR	WI_Param;
	APTR	CH_Lacs;
	APTR	CH_Riv;
	APTR	CH_LonLat;
	APTR	CH_Noms;
	APTR	CH_Coord;
	APTR	CH_Fill_Pays;
	APTR	CH_Elements;
	APTR	CH_Trajectoires;
	APTR	CH_Distance;
	APTR	CH_Scale;
	APTR	CH_Area;
	APTR	SL_x;
	APTR	SL_y;
	APTR	SL_z;
	APTR	IM_Rectangle;
	APTR	WI_Sel_Cty;
	APTR	LV_Pays;
	APTR	WI_Cmd_Panel;
	APTR	BT_Move;
	APTR	BT_Show_Pt;
	APTR	BT_Show_Seg;
	APTR	BT_Edit;
	APTR	BT_Create_Pays;
	APTR	BT_New_Border;
	APTR	BT_New_Point;
	APTR	BT_End_Border;
	APTR	STR_Nom_Border;
	APTR	STR_Code;
	APTR	SL_Code_Point;
	APTR	WI_Sel_Cont;
	APTR	LV_Continent;
	APTR	WI_Chargement;
	APTR	PA_chargement_fond;
	APTR	STR_PA_chargement_fond;
	APTR	BT_Redraw_Ext_Data;
	APTR	BT_Effacer_Fond;
	APTR	WI_Sel_Elem;
	APTR	LV_Elements;
	APTR	TX_Selected_Element;
	APTR	TX_Pays;
	APTR	TX_Latitude;
	APTR	TX_Longitude;
	APTR	TX_Caracteristique;
	APTR	BT_Element_Origine;
	APTR	BT_Element_Destination;
	APTR	WI_Param_Datas;
	APTR	RA_Type_Data;
	APTR	STR_fichier_Donnee;
	APTR	IM_Fichier_Donnee;
	APTR	LV_Data1;
	APTR	RA_label_4;
	APTR	LV_Data2;
	APTR	STR_Coef;
	APTR	BT_Maj;
	APTR	BT_Ajouter_Donnee;
	APTR	BT_Effacer;
	APTR	WI_Datas;
	APTR	LV_Deselect;
	APTR	BT_Vers_Deselect;
	APTR	BT_Vers_Select;
	APTR	LV_Select;
	APTR	BT_Continent;
	APTR	BT_Petits_Pays;
	APTR	BT_Tout_Des;
	APTR	BT_Tout_Sel;
	APTR	RA_Type_Graph;
	APTR	LV_Datas;
	APTR	BT_Editer;
	APTR	BT_Supprimer;
	APTR	BT_Ajouter;
	APTR	BT_Ok_Datas;
	APTR	WI_Trajectoire;
	APTR	STR_Trajectoire_Fichier;
	APTR	IM_Trajectoire_Choix;
	APTR	BT_Trajectoire_OK;
	APTR	BT_Trajectoire_Cancel;
	APTR	PA_chargement_trajectoire;
	APTR	STR_PA_chargement_trajectoire;
	APTR	WI_Organisation;
	APTR	CY_organisation;
	APTR	TX_organisation_officiel;
	APTR	LV_organisation;
	APTR	WI_Info_Element;
	APTR	TX_nom_element;
	APTR	TX_type_element;
	APTR	TX_pays_element;
	APTR	TX_longitude_element;
	APTR	TX_latitude_element;
	APTR	TX_caracteristique_element;
	APTR	BT_voir_donnee_externe;
	APTR	WI_Classement;
	APTR	TX_classement;
	APTR	LV_classement;
	APTR	WI_Info;
	char *	STR_TX_lon;
	char *	STR_TX_lat;
	char *	STR_TX_Selectionne;
	char *	STR_TX_courant;
	char *	STR_TX_Selected_Element;
	char *	STR_TX_Pays;
	char *	STR_TX_Latitude;
	char *	STR_TX_Longitude;
	char *	STR_TX_Caracteristique;
	char *	STR_TX_organisation_officiel;
	char *	STR_TX_nom_element;
	char *	STR_TX_type_element;
	char *	STR_TX_pays_element;
	char *	STR_TX_longitude_element;
	char *	STR_TX_latitude_element;
	char *	STR_TX_caracteristique_element;
	char *	STR_TX_classement;
	char *	CY_ProjContent[5];
	char *	RA_Type_DataContent[3];
	char *	RA_label_4Content[5];
	char *	RA_Type_GraphContent[5];
	char *	CY_organisationContent[2];
};


extern struct ObjApp * CreateApp(void);
extern void DisposeApp(struct ObjApp *);
